//
//  DashboardModels.swift
//  RickMortyApp
//
//  Created by Nevilkumar Lad on 05/01/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

let CHARACTERS = "Characters"
let EPISODES = "Episodes"
let LOCATIONS = "Locations"

enum Actions {
    case characters
    case episodes
    case locations
    case none

    var title: String {
        switch self {
        case .characters: return CHARACTERS
        case .episodes: return EPISODES
        case .locations: return LOCATIONS
        case .none: return ""
        }
    }
}

enum DashboardLoaderType {
    case general
}

enum DashboardErrorType {
    case backend
}

enum DashboardModels {

    // MARK: - Use Cases

    enum FetchFromLocalDataStore {
        struct Request {
        }

        struct Response {
            var actionItems: [[String: String]]
        }

        struct ViewModel {
            struct DispalyedAction {
                var action: Actions
                var title: String
                var icon: String
            }

            var displayedActions: [DispalyedAction]
        }
    }

    enum FetchFromRemoteDataStore {
        struct Request {
        }

        struct Response {
            var exampleVariable: String?
        }

        struct ViewModel {
            var exampleVariable: String?
        }
    }
}
