//
//  DashboardRouter.swift
//  RickMortyApp
//
//  Created by Nevilkumar Lad on 05/01/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DashboardRoutingLogic {
    func showNextScene(action: Actions)
}

protocol DashboardDataPassing {
    var dataStore: DashboardDataStore? { get }
}

class DashboardRouter: NSObject, DashboardRoutingLogic, DashboardDataPassing {
    weak var viewController: DashboardViewController?
    var dataStore: DashboardDataStore?

    // MARK: Navigation
    func showNextScene(action: Actions) {
        //Set selection action to the data store

    }
}

// MARK: Passing data
extension DashboardRouter {

    /*
    func passDataTo(_ destinationDS: inout <destinationDataStore>?, from sourceDS: DashboardDataStore?) {

    }
    */
}
