//
//  DetailModels.swift
//  RickMortyApp
//
//  Created by Nevilkumar Lad on 06/01/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
enum DetailType {
    case characters
    case episodes
    case locations
}

enum DetailLoaderType {
    case general
}

enum DetailErrorType {
    case backend
    case custom(message: String)
}

enum DetailModel {
    // MARK: Use cases

    enum DetailDetails {
        struct Request {
        }
        struct Response {
        }
        struct ViewModel {
        }
    }

    enum NextScene {
        struct Request {
        }
        struct Response {
        }
        struct ViewModel {
        }
    }
}
