//
//  DetailRouter.swift
//  RickMortyApp
//
//  Created by Nevilkumar Lad on 06/01/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DetailRoutingLogic {
    func showNextScene()
}

protocol DetailDataPassing {
    var dataStore: DetailDataStore? { get }
}

class DetailRouter: NSObject, DetailRoutingLogic, DetailDataPassing {
    weak var viewController: DetailViewController?
    var dataStore: DetailDataStore?

    // MARK: Navigation
    func showNextScene() {

    }
}

// MARK: Passing data
extension DetailRouter {

    /*
    func passDataTo(_ destinationDS: inout <destinationDataStore>?, from sourceDS: DetailDataStore?) {

    }
    */
}
